test:
  service: Disk
  root: <%= Rails.root.join("tmp/storage") %>

local:
  service: Disk
  root: <%= Rails.root.join("storage") %>

amazon:
  service: S3
  access_key_id: '<%= ENV["AWS_ACCESS_KEY_ID"] %>'  # Use environment variables for credentials
  secret_access_key: '<%= ENV["AWS_SECRET_ACCESS_KEY"] %>'  # Use environment variables for credentials
  region: 'ap-southeast-1'  # Replace with your AWS region
  bucket: 'file-management-bucket-ftr'  # Same bucket for both dev and prod

production:
  service: S3
  access_key_id: '<%= ENV["AWS_ACCESS_KEY_ID"] %>'  # Use environment variables for credentials
  secret_access_key: '<%= ENV["AWS_SECRET_ACCESS_KEY"] %>'  # Use environment variables for credentials
  region: 'ap-southeast-1'  # Same region as in amazon config
  bucket: 'file-management-bucket-ftr'  # Same bucket for both dev and prod
